version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8000:8080"
    environment:
      SWAGGER_JSON: /tmp/openapi.yaml
    volumes:
      - ../docs/openapi.spec.yaml:/tmp/openapi.yaml:ro
