version: '3.8'

services:
  dd-agent:
    image: datadog/agent:7.55.1
    container_name: dd-agent
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512m
    ports:
      - "4317:4317/tcp"
      - "4318:4318/tcp"
      - "8126:8126/tcp"
      - "8125:8125/udp"
    environment:
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_PROCESS_AGENT_ENABLED=false
      # OLTP
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_METRICS_ENABLED=true
      - DD_OTLP_CONFIG_TRACES_ENABLED=true
      # DB Queries
      - DD_APM_COMPUTE_STATS_BY_SPAN_KIND=true 
      - DD_APM_PEER_TAGS_AGGREGATION=true
      # Logs
      - DD_LOGS_ENABLED=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    env_file:
      - ../.envs/datadog.env
